spring:
  application:
    name:
      movie-service
  datasource:
    url: jdbc:mysql://localhost:3306/springdb
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
  grpc:
    server:
      port: 9092
jwt:
  access:
    key: tuandeptraiiuadysfhashdfkahsdfkjhasjdfhkjasdhdf
    expiration: 43200000
  refresh:
    key: tuandeptraiiuadysfhashdfkahsdfkjhasjdfhkjasdhdf
    expiration: 1296000000
  rotation:
    key: tuandeptraiiuadysfhashdfkahsdfkjhasjdfhkjasdhdf
    expiration: 43200000
